services:
  actix:
    image: mxr/video-to-gif:latest
    container_name: video-to-gif
    restart: unless-stopped
    ports:
      - 4340:4340
    volumes:
      - ./certs:/usr/src/video-to-gif/certs
      - ./config.toml:/usr/src/video-to-gif/config.toml
