

name: Build

on:
  pull_request:
    branches: [ prod ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Touch placeholder files
        run: |
          touch config.toml
          mkdir certs

      - name: Build image
        run: build.sh
